# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  barong_client_id: <%= ENV.fetch('BARONG_CLIENT_ID') %>
  barong_client_secret: <%= ENV.fetch('BARONG_CLIENT_SECRET') %>

development:
  secret_key_base: 7d63854c285e761724d35ef3f110f49957e94d8e7d4f919d414080de6c9829aea5472d1f2a563589cf147115a6c546a69b30a447e83acbd41fdaef2b53816bf8
  # barong_client_id: 0000000000000000000000000000000000000000
  # barong_client_secret: 0000000000000000000000000000000000000000

test:
  secret_key_base: 978093bac3bcc6a7b5dfc2ea8a33d21a0bcd2454365738fce38ca1a1fbce9d5e8f47cbd062fed83cd14bcb9796563137c290732684c3d8ef86376d6c47c92eec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
